db.url=jdbc:mysql://mysql-228dab1a-cuneytbaskurt123-b23f.d.aivencloud.com:21158/defaultdb?useSSL=true&trustServerCertificate=true
mysql.host=mysql-228dab1a-cuneytbaskurt123-b23f.d.aivencloud.com
mysql.port=21158
mysql.username=avnadmin
mysql.password=AVNS_4dZc7eBKGGbJUyoYhnF
mysql.database=defaultdb

neo4j.uri=bolt://127.0.0.1:7687
neo4j.user=neo4j
neo4j.password=Mellon21.